export const STRINGS = {
  common: {
    confirmed: 'Đã xác nhận',
    pending: 'Đang chờ',
    cancelled: 'Đã hủy',
    loading: 'Đang tải...',
    error: 'Đã có lỗi xảy ra',
    retry: 'Thử lại',
    close: 'Đóng',
    back: 'Quay lại',
    save: 'Lưu',
    edit: 'Sửa',
    delete: 'Xóa',
    confirm: 'Xác nhận',
    share: 'Chia sẻ',
    later: 'Để sau',
    login: 'Đăng nhập',
    got_it: 'Đã hiểu',
    great: 'Tuyệt vời',
    stay: 'Ở lại',
    keep: 'Giữ lại',
    yes: 'Có',
    no: 'Không',
    you: 'Bạn',
    person: 'người',
    view: 'Xem',
    countdown: {
      starting_soon: 'Sắp bắt đầu',
      prefix: 'Còn',
      hours_suffix: 'h',
      minutes_suffix: 'p',
    },
    booking_info: 'Thông tin đặt sân',
    host_only_visibility: 'Chỉ bạn (host) nhìn thấy phần này',
    booking_ref: 'Mã đặt sân',
    booking_name: 'Tên đặt sân',
    phone_number: 'Số điện thoại',
    gender: {
      male: 'Nam',
      female: 'Nữ',
      any: 'Bất kỳ',
    },
    validation: {
      name_required: 'Vui lòng nhập họ và tên.',
      name_min_length: 'Họ tên cần tối thiểu 2 ký tự.',
      name_invalid: 'Họ tên chỉ nên gồm chữ cái.',
      phone_required: 'Vui lòng nhập số điện thoại.',
      phone_invalid: 'SĐT không hợp lệ. Dùng 10 số (0xxxxxxxxx) hoặc 84xxxxxxxxx.',
      generic_error: 'Vui lòng kiểm tra lại thông tin.',
    },
  },
  session: {
    status: {
      open: 'Đang mở',
      full: 'Đã đầy',
      starting_soon: 'Sắp bắt đầu',
      past: 'Đã kết thúc',
      cancelled: 'Đã hủy',
      in_progress: 'Đang diễn ra',
    },
    booking: {
      confirmed: 'Đã đặt sân',
      unconfirmed: 'Chưa đặt sân',
      waiting: 'Đang chờ xác nhận',
      booking_confirmed_status: 'Đã đặt sân',
      booking_unconfirmed_status: 'Chưa đặt sân',
    },
    roles: {
      host: 'Chủ kèo',
      player: 'Thành viên',
    },
    actions: {
      join: 'Vào kèo',
      leave: 'Rời kèo',
      cancel_request: 'Hủy yêu cầu',
      review_requests: 'Duyệt yêu cầu',
      edit_session: 'Sửa kèo',
      report_result: 'Báo kết quả',
      confirm_result: 'Xác nhận kết quả',
    },
    labels: {
      match_level: '✓ khớp với bạn',
      remaining_slots: 'còn {count} chỗ',
      remaining_slots_last: 'còn 1 chỗ duy nhất',
      full: 'Đủ người',
      need_players: 'Cần người gấp',
      per_person: '/người',
      free: 'Miễn phí',
      singles: 'Đánh đơn',
      doubles: 'Đánh đôi',
      level_prefix: 'Level',
      not_match: 'chưa khớp',
      joined_count: 'đã vào',
      upcoming_match: 'KÈO SẮP TỚI',
      starts_at: 'Bắt đầu lúc',
      waiting_more: 'chờ {count} nữa',
      cancelled_no_players: 'Kèo bị hủy do không đủ người',
      cancelled_generic: 'Kèo đã bị hủy',
      edit_result: 'Sửa kết quả',
      awaiting_confirmation: 'Đang chờ xác nhận',
      input_result: 'Nhập kết quả trận',
      in_progress_match: 'Kèo đang diễn ra',
      players_count: '{count}/{total} người chơi',
      partial_player_warning: 'Trận đấu chỉ có {count}/{max} {person}. Nếu trận đấu vẫn diễn ra, bạn có thể tiếp tục báo kết quả.',
    },
    buttons: {
      view_result: 'XEM KẾT QUẢ TRẬN',
      rate_match: 'ĐÁNH GIÁ TRẬN ĐẤU',
      saving: 'ĐANG LƯU...',
      edit_session: 'SỬA KÈO',
      save_changes: 'LƯU THAY ĐỔI',
      arranging: 'ĐANG XẾP ĐỘI',
      cancelling: 'Đang hủy...',
      cancel_session: 'Hủy kèo',
      confirm_result: 'XÁC NHẬN KẾT QUẢ',
      leaving: 'ĐANG RỜI...',
      leave_session: 'RỜI KÈO',
    },
  },
  home: {
    greeting: {
      morning: 'Chào buổi sáng',
      afternoon: 'Chào buổi chiều',
      evening: 'Chào buổi tối',
      default: 'Xin chào',
    },
    prompts: {
      ready: 'Đã sẵn sàng ra sân chưa?',
      join_today: 'Hôm nay ra sân chứ?',
    },
    inbox: {
      title: 'Việc cần chốt',
      tasks_count: '{count} việc đang chờ',
      status: {
        need_confirmation: 'CẦN XÁC NHẬN',
        need_result: 'CẦN NHẬP KẾT QUẢ',
        disputed: 'KẾT QUẢ BỊ KHIẾU NẠI',
        need_rating: 'CẦN ĐÁNH GIÁ',
      },
      actions: {
        confirm: 'Xác nhận',
        submit: 'Nhập ngay',
        edit: 'Sửa ngay',
        rate: 'Đánh giá',
      },
      deadline: {
        waiting: 'Hạn nhập: đang chờ',
        overdue: 'Quá hạn {time}',
        remaining: 'Hạn nhập: còn {time}',
      },
    },
    streak: {
      days: '{count} ngày',
      remaining_badge: '{count} ngày nữa lên huy hiệu',
      label: 'CHUỖI',
    },
    sections: {
      streak: 'CHUỖI RA SÂN',
      personalized: 'Dành riêng cho bạn',
      personalized_sub: 'Gợi ý hợp gu',
      rescue: 'Cứu nét khẩn cấp',
      rescue_sub: 'Cần người gấp',
      familiar_courts: 'Sân ở gần bạn',
      familiar_courts_sub: 'Sân ở gần',
      upcoming: 'Trận của bạn',
      upcoming_sub: 'Sắp diễn ra',
    },
    actions: {
      create_session: 'Tạo kèo mới',
      view_session: 'XEM KÈO',
      join_session: 'VÀO KÈO',
      prioritize_match: 'ƯU TIÊN GHÉP',
      ready: 'Sẵn sàng',
    },
    status: {
      open_matches: '{count} kèo đang mở',
    },
    pending_results: {
      disputed_title: 'Kết quả bị khiếu nại',
      required_title: 'Cần nhập kết quả',
      fix_now: 'SỬA NGAY',
      enter_now: 'NHẬP NGAY',
      swipe_hint: 'Vuốt để xem thêm',
    },
  },
  find_session: {
    title: 'TÌM KÈO',
    search_placeholder: 'Tìm theo tên sân, địa chỉ...',
    filters: {
      title: 'Bộ lọc',
      skill_level: 'Trình độ',
      date: 'Ngày chơi',
      court: 'Sân đấu',
      reset: 'Thiết lập lại',
      apply: 'Áp dụng',
    },
    empty: {
      no_results: 'Không tìm thấy kèo nào',
      no_results_sub: 'Thử thay đổi bộ lọc hoặc khu vực tìm kiếm khác xem sao nhé.',
      avg_elo: 'TB {avgElo} ELO',
      waiting_status: 'Đang chờ...',
      empty_slot: 'Vị trí trống',
      match_list: 'Danh sách thi đấu',
      done: 'Xong',
      arrange_teams: 'Chỉnh đội',
      arrange_hint: 'Nhấn icon đổi đội để chuyển người chơi giữa Đội A và Đội B.',
      auto_balance: 'Chia đội tự động',
    },
    sort: {
      relevance: 'Độ phù hợp',
      time: 'Giờ chơi',
    },
    filtering: {
      nearby: 'Đang lọc theo sân quen',
      selected_court: 'Sân đã chọn',
      clear: 'Bỏ lọc',
    },
    status: {
      matches_found: '{count} kèo phù hợp',
      searching: 'Đang săn kèo...',
      refreshing: 'Săn kèo mới...',
    },
    advanced_filter: {
      title: 'BỘ LỌC NÂNG CAO',
      reset: 'Đặt lại',
      apply: 'Áp dụng bộ lọc',
      district: 'Quận/Huyện',
      date: 'Ngày',
      weekend: 'Cuối tuần',
      quick_dates: {
        today: 'Hôm nay',
        tomorrow: 'Ngày mai',
        sat: 'Thứ 7',
        sun: 'Chủ nhật',
      },
      select_date: 'Chọn ngày',
      time_slot: 'Khung giờ',
      time_slots: {
        morning: 'Sáng',
        afternoon: 'Chiều',
        evening: 'Tối',
      },
      skill_level: 'Trình độ',
      price: 'Giá/người',
      price_from: 'Từ',
      price_to: 'Đến',
      any: 'Bất kỳ',
      price_error: 'Giá tối thiểu không được lớn hơn giá tối đa',
      court_status: 'Trạng thái sân',
      slots_left: 'Còn ít nhất',
      slots_suffix: '{count} chỗ',
    },
  },
  create_session: {
    title: 'TẠO KÈO MỚI',
    actions: {
      submit: 'Tạo kèo',
      save: 'Lưu thay đổi',
    },
  },
  profile: {
    title: 'HỒ SƠ',
    edit_title: 'SỬA HỒ SƠ',
    sections: {
      info: 'THÔNG TIN',
      skill: 'TRÌNH ĐỘ',
      connection: 'KHỚP KÈO NHANH',
      overview: 'TỔNG QUAN',
      community: 'CỘNG ĐỒNG',
      achievements: 'DANH HIỆU',
      courts: 'SÂN QUEN',
      history: 'LỊCH SỬ',
      account: 'TÀI KHOẢN',
      settings: 'CÀI ĐẶT',
      pvna: 'TRÌNH ĐỘ PVNA',
      favorite_courts: 'SÂN HAY CHƠI',
      account_mgmt: 'QUẢN LÝ TÀI KHOẢN',
      empty_courts: 'Chưa có dữ liệu sân đã chơi',
      matches_count: '{count} TRẬN',
    },
    fields: {
      name: 'Tên',
      bio: 'Giới thiệu',
      city: 'Thành phố',
      auto_accept: 'Tự động nhận kèo phù hợp',
    },
    placeholders: {
      bio: 'Viết vài dòng về bạn...',
    },
    stats: {
      matches: 'Trận đấu',
      hosted: 'Đã host',
      reliability: 'Độ tin cậy',
      joined_year: 'Thành viên từ',
    },
    actions: {
      edit: 'Sửa hồ sơ',
      logout: 'Đăng xuất',
      redo_assessment: 'Làm lại đánh giá',
      save: 'Lưu thay đổi',
      cancel: 'Hủy thay đổi',
      save_changes: 'Lưu thay đổi',
      cancel_changes: 'Hủy thay đổi',
      host_mode: 'Chế độ Host',
      logout_confirm: 'Bạn chắc muốn đăng xuất không?',
      activate_host_title: 'KÍCH HOẠT CHẾ ĐỘ HOST',
      activate_host_msg: 'Bạn có muốn kích hoạt quyền Chủ sân để bắt đầu tạo kèo và quản lý trận đấu không?',
      activate_host_btn: 'KÍCH HOẠT NGAY',
    },
    status: {
      saved: 'Đã lưu',
    },
    errors: {
      max_courts: 'Đã đạt giới hạn sân yêu thích',
    },
    empty: {
      no_courts: 'Chưa có sân yêu thích',
      no_courts_sub: 'Thêm sân bạn hay chơi để nhận gợi ý kèo phù hợp hơn.',
      login_required: 'Đăng nhập để xem hồ sơ',
      login_required_sub: 'Quản lý thông tin cá nhân và lịch sử tham gia kèo của bạn ở một nơi gọn gàng hơn.',
      login_button: 'Đăng nhập',
      not_found: 'Không tìm thấy hồ sơ',
      not_found_sub: 'Thử tải lại hoặc đăng nhập lại để tiếp tục.',
    },
    history: {
      title: 'LỊCH SỬ TRẬN ĐẤU',
      empty: 'Chưa có trận đấu nào',
      empty_sub: 'Tham gia các kèo đấu để bắt đầu xây dựng lịch sử thi đấu của bạn.',
      host_label: 'Host',
      player_label: 'Người chơi',
    },
    labels: {
      reliability: 'TIN CẬY',
      verified: 'XÁC MINH',
      placement: 'TRẬN PHÂN HẠNG',
      joined_since: 'Thành viên từ',
      no_bio: 'Chưa có mô tả bản thân.',
      updating: 'Đang cập nhật...',
      starting_level: 'Mức khởi điểm',
      level_description: 'Mô tả trình độ',
      update_profile_refresh: 'Cập nhật hồ sơ...',
      logout_confirm: 'Bạn chắc muốn đăng xuất không?',
      adjusting: 'Đang hiệu chỉnh',
      adjusting_description: 'Hệ thống đang dùng Elo và tín hiệu sau trận để tinh chỉnh nhịp ghép kèo phù hợp hơn.',
    },
    achievements: {
      title: 'Kho Danh Hiệu',
      unlocked_count: '{count}/{total} danh hiệu đã mở khóa',
      not_earned: 'Chưa mở khóa',
      categories: {
        progression: 'Tiến trình',
        performance: 'Thành tích',
        momentum: 'Phong độ',
        conduct: 'Uy tín',
      },
      requirements: {
        active_member_20: 'Chơi đủ 20 trận',
        giant_slayer: 'Thắng một kèo lệch +100 Elo',
        golden_host: 'Chủ kèo được đánh giá 4.9+',
        win_streak_3: 'Đạt chuỗi thắng 3 trận',
      },
    },
    feedback: {
      labels: {
        fair_play: 'Chơi đẹp',
        on_time: 'Đúng giờ',
        friendly: 'Thân thiện',
        skilled: 'Kỹ thuật tốt',
        good_description: 'Mô tả rõ ràng',
        well_organized: 'Tổ chức tốt',
        fair_pairing: 'Xếp cặp công bằng',
        toxic: 'Xấu tính',
        late: 'Đến trễ',
        dishonest: 'Gian lận điểm',
        court_mismatch: 'Sân sai mô tả',
        poor_organization: 'Tổ chức kém',
      },
      contexts: {
        fair_play: 'Thường được nhắc đến vì fair-play và giữ nhịp trận rất tốt.',
        on_time: 'Có mặt đúng hẹn và giữ nhịp vào sân khá ổn định.',
        friendly: 'Tạo cảm giác dễ chơi chung và giao tiếp khá thoải mái.',
        skilled: 'Được đánh giá cao về cảm giác bóng và độ ổn định khi vào trận.',
        good_description: 'Nếu là chủ kèo, người này thường lên kèo rõ và đúng mô tả.',
        well_organized: 'Có xu hướng giữ đội hình, lịch và flow trận khá mượt.',
        fair_pairing: 'Thường được ghi nhận ở khả năng cân đội khi làm chủ kèo.',
        toxic: 'Đôi lúc phản ứng căng khi trận đấu hoặc tranh điểm nóng lên.',
        late: 'Có vài phản hồi về việc đến sát giờ hoặc làm đội hình chờ.',
        dishonest: 'Cần cẩn thận hơn ở các tình huống gọi điểm và xác nhận bóng.',
        court_mismatch: 'Nếu là chủ kèo, đôi lúc chất lượng sân thực tế không khớp mô tả ban đầu.',
        poor_organization: 'Một số phản hồi cho thấy nhịp tổ chức trận còn thiếu mượt.',
      },
      record_suffix: 'ghi nhận',
    },
    badge_default_desc: 'Danh hiệu mở khóa từ kết quả và uy tín trong hệ thống.',
    badge_default_req: 'Đạt mốc hệ thống',
    header: 'HỒ SƠ NGƯỜI CHƠI',
    login_required: {
      title: 'Đăng nhập để xem hồ sơ',
      description: 'Quản lý thông tin cá nhân và lịch sử tham gia kèo của bạn ở một nơi gọn gàng hơn.',
      login_btn: 'Đăng nhập',
    },
    not_found: {
      title: 'Không tìm thấy hồ sơ',
      description: 'Thử tải lại hoặc đăng nhập lại để tiếp tục.',
    },
  },
  onboarding: {
    complete: 'Hoàn tất',
    next: 'Tiếp theo',
    start: 'Bắt đầu ngay',
    title: 'PHÂN LOẠI TRÌNH ĐỘ',
    step_label: 'BƯỚC',
    result_title: 'KẾT QUẢ TỰ ĐÁNH GIÁ',
    initial_elo: 'Elo khởi điểm dự kiến',
    redo_quiz: 'LÀM LẠI QUIZ',
    view_result: 'Xem kết quả',
    confirm_level: 'XÁC NHẬN MỨC NÀY',
    submit_error: 'Không thể lưu kết quả lúc này. Vui lòng thử lại sau ít phút.',
    placement_title: 'QUY TẮC ĐÁNH GIÁ',
    placement_note: 'Bạn sẽ trải qua 5 trận đấu thử thách (Placement) để hệ thống xác định trình độ chính xác. Chỉ các trận đôi (4 người) mới được tính điểm vào thứ hạng Elo.',
    personal_info_title: 'THÔNG TIN CÁ NHÂN',
    personal_info_sub: 'Vui lòng hoàn thiện thông tin để bắt đầu tham gia cộng đồng Pickleball.',
    field_name: 'Họ và tên',
    field_phone: 'Số điện thoại',
    field_email: 'Email',
    validation_error: 'Vui lòng điền đầy đủ và chính xác thông tin.',
    placeholders: {
      name: 'Nguyễn Văn A',
      phone: '0901234567',
      email: 'a@example.com',
    },
    errors: {
      no_account: 'Không tìm thấy tài khoản hiện tại.',
    },
    assessment: {
      time_playing: {
        question: 'Bạn đã chơi pickleball bao lâu?',
        options: {
          none: 'Chưa lần nào',
          beginner: 'Mới thử 1–2 lần',
          intermediate: 'Được vài tháng rồi',
          advanced: 'Hơn 1 năm',
          expert: 'Chơi lâu, khá đều',
        },
      },
      sport_background: {
        question: 'Bạn có nền tảng môn vợt nào không?',
        subtitle: 'Cầu lông, tennis, bóng bàn... giúp làm quen pickleball nhanh hơn',
        options: {
          none: 'Không có',
          pingpong: 'Bóng bàn',
          badminton: 'Cầu lông',
          tennis: 'Tennis',
          other: 'Môn khác',
        },
      },
      rally: {
        question: 'Khi đánh bóng qua lưới, bạn thấy mình thế nào?',
        subtitle: 'Rally = đánh qua đánh lại nhiều lần mà không rớt bóng',
        options: {
          fail: 'Hay đánh hỏng, bóng vào lưới hoặc ra ngoài',
          unstable: 'Qua lưới được nhưng chưa ổn định',
          stable: 'Rally ổn, kiểm soát được hướng bóng',
          proactive: 'Chủ động chọn góc, ít mắc lỗi',
        },
      },
      kitchen: {
        question: 'Bạn xử lý bóng ở kitchen như thế nào?',
        subtitle: 'Kitchen = vùng sát lưới 2 bên — nơi diễn ra hầu hết điểm quyết định. Dink = đánh nhẹ, thấp qua lưới',
        options: {
          unknown: 'Chưa rõ luật vùng này',
          faulty: 'Biết luật nhưng hay bị lỗi',
          dink_stable: 'Dink tương đối ổn',
          pressure: 'Kiểm soát tốt, tạo áp lực được',
        },
      },
      overhead: {
        question: 'Khi bóng lob cao qua đầu, bạn xử lý sao?',
        subtitle: 'Lob = đối thủ đánh bóng vọt cao qua đầu bạn. Overhead smash = đập bóng từ trên xuống',
        options: {
          fail: 'Chạy không kịp hoặc đánh hỏng',
          weak: 'Chạy được nhưng trả bóng yếu',
          smash_unstable: 'Overhead smash được, đôi khi chưa ổn',
          smash_proactive: 'Smash chủ động, chọn góc tốt',
        },
      },
      win_rate: {
        question: 'Bạn thường thắng hay thua khi chơi?',
        options: {
          learn: 'Chủ yếu thua, đang học',
          less: 'Thua nhiều hơn thắng',
          equal: 'Thắng thua ngang nhau',
          more: 'Thắng nhiều trong nhóm hay chơi',
          pro: 'Thường thắng, đã thử ở giải phong trào',
        },
      },
      play_preference: {
        question: 'Bạn muốn ghép kèo với ai?',
        subtitle: 'Dùng để tìm kèo phù hợp hơn cho bạn',
        options: {
          beginner: 'Người mới như mình để cùng học',
          higher: 'Người nhỉnh hơn để tiến bộ nhanh',
          fun: 'Ai cũng được, miễn vui',
          serious: 'Người cùng trình để đánh nghiêm túc',
        },
      },
    },
  },
  auth: {
    login_title: 'Đăng nhập',
    otp_title: 'Xác thực OTP',
    phone_sub: 'Sử dụng số điện thoại để tiếp tục',
    otp_sub: 'Mã đã gửi tới',
    phone_placeholder: 'Nhập số điện thoại',
    phone_hint: 'Chúng tôi sẽ gửi một mã xác thực 6 số qua SMS để bảo mật tài khoản của bạn.',
    resend_otp: 'Gửi lại mã xác thực',
    change_phone: 'Đổi số điện thoại',
    submit_phone: 'Tiếp tục →',
    submit_otp: 'Xác nhận',
    processing: 'Đang xử lý...',
    trust_title: 'Bảo mật tuyệt đối',
    trust_sub: 'Thông tin của bạn được mã hóa và bảo mật theo tiêu chuẩn cao nhất.',
    no_account: 'Chưa có tài khoản?',
    join_now: 'Tham gia ngay',
  },
  session_detail: {
    title: 'CHI TIẾT KÈO',
    default_title: 'Kèo Pickleball',
    free: 'Miễn phí',
    open_slots: 'Đã có {count} người tham gia',
    ended: 'KẾT THÚC',
    share_message: 'Tham gia kèo pickleball này nhé! {url}',
    share_failed_desc: 'Vui lòng thử lại sau ít phút.',
    roster_title: 'DANH SÁCH THAM GIA',
    action: {
      joined: 'ĐÃ THAM GIA',
      join: 'THAM GIA NGAY',
    },
    status: {
      updated: 'Đã cập nhật thông tin kèo',
    },
    meta: {
      time: 'Thời gian',
      cost: 'Chi phí',
      notes: 'Ghi chú',
    },
    result: {
      team_a: 'Đội A',
      team_b: 'Đội B',
      page_title: 'KẾT QUẢ TRẬN ĐẤU',
      confirm_title: 'Xác nhận kết quả',
      win: 'THẮNG',
      loss: 'THUA',
      draw: 'HÒA',
      dispute_title: 'Khiếu nại kết quả',
      dispute_placeholder: 'Nhập lý do khiếu nại...',
      dispute_content: 'Nội dung khiếu nại',
      dispute_action: 'Khiếu nại',
      confirm_action: 'Xác nhận',
      share: 'Chia sẻ',
      status: {
        confirmed: 'Bạn đã xác nhận kết quả',
        disputed: 'Bạn đã khiếu nại kết quả',
      },
    },
    elo_banner: {
      title: 'KÈO TÍNH ĐIỂM ELO',
      description: 'Kết quả trận đấu này sẽ ảnh hưởng đến trình độ (Elo) của bạn.',
    },
    errors: {
      load_failed: 'Không thể tải thông tin kèo',
      not_found: 'Không tìm thấy thông tin kèo hoặc kèo đã bị xóa.',
      share_failed: 'Không thể chia sẻ kèo',
      results_submitted: 'Kết quả đã được gửi và đang chờ người chơi xác nhận.',
      results_finalized: 'Kết quả đã được chốt và không thể thay đổi',
      dispute_from_players: 'Nội dung khiếu nại từ người chơi',
      additional_notes: 'Ghi chú thêm',
      notes_placeholder: 'Ví dụ: Trận đấu rất kịch tính, mọi người chơi đều rất fair-play...',
    },
  },
  session_join: {
    dialogs: {
      login_required: {
        title: 'Yêu cầu đăng nhập',
        message: 'Bạn cần đăng nhập để tham gia kèo này.',
      },
      login_required_request: 'Bạn cần đăng nhập để gửi yêu cầu tham gia.',
      deadline_passed: {
        title: 'Hết hạn đăng ký',
        message: 'Thời gian đăng ký tham gia kèo này đã kết thúc.',
      },
      join_failed: {
        title: 'Tham gia thất bại',
      },
      join_success: {
        title: 'Tham gia thành công',
        message: 'Chào mừng bạn đến với kèo! Hãy chuẩn bị sẵn sàng nhé.',
      },
      request_failed: {
        title: 'Gửi yêu cầu thất bại',
      },
      request_success: {
        title: 'Đã gửi yêu cầu',
        message: 'Yêu cầu của bạn đã được gửi tới host. Vui lòng chờ phản hồi nhé.',
      },
      waitlist_success: {
        title: 'Đã đăng ký dự bị',
        message: 'Bạn đã được thêm vào danh sách dự bị. Chúng tôi sẽ báo nếu có chỗ trống!',
      },
      leave_session: {
        title: 'Rời kèo',
        message: 'Bạn có chắc chắn muốn rời khỏi kèo này không?',
        confirm: 'Rời kèo',
      },
      leave_failed: {
        title: 'Rời kèo thất bại',
      },
      cancel_session: {
        title: 'Hủy kèo',
        message: 'Bạn là host. Việc hủy kèo sẽ thông báo tới tất cả thành viên. Bạn chắc chứ?',
        confirm: 'Hủy kèo',
      },
      cancel_failed: {
        title: 'Hủy kèo thất bại',
      },
      cancel_request: {
        title: 'Hủy yêu cầu',
        message: 'Bạn có muốn hủy yêu cầu tham gia kèo này không?',
        confirm: 'Hủy yêu cầu',
      },
      waitlist_confirm: {
        title: 'Kèo đã đầy',
        message: 'Kèo hiện đã đầy và bạn sẽ vào danh sách dự bị. Chủ kèo sẽ liên hệ nếu có slot trống gần giờ chơi. Bạn vẫn muốn đăng ký chứ?',
        cancel: 'Bỏ qua',
        confirm: 'Đăng ký dự bị',
      },
      skill_warning: {
        title: 'Chênh lệch trình độ',
        message: 'Trình độ của bạn thấp hơn yêu cầu của kèo này ({diff} PVNA). Bạn vẫn muốn tham gia chứ?',
        cancel: 'Bỏ qua',
        confirm: 'Tham gia ngay',
      },
    },
    button: {
      waiting_host: 'Đang chờ host phản hồi',
      waiting_host_sub: 'Yêu cầu tham gia của bạn đã được gửi. Host sẽ xem và phản hồi sớm.',
      recent_message: 'Tin nhắn gần nhất',
      cancel_request: 'Hủy yêu cầu tham gia',
      rejected: 'Yêu cầu trước đó đã bị từ chối',
      host_feedback: 'Phản hồi từ host',
      join_now: 'Tham gia ngay',
      register_waitlist: 'Đăng ký dự bị',
      request_join: 'Xin vào kèo',
    },
    errors: {
      cancel_request_failed: 'Không thể hủy yêu cầu: ',
    },
  },
  join_modal: {
    request: {
      eyebrow: 'YÊU CẦU THAM GIA',
      title: 'XIN VÀO KÈO',
      description: 'Kèo này cần sự đồng ý của host. Hãy gửi lời chào và chờ host xác nhận nhé!',
      submit: 'Gửi yêu cầu',
    },
    waitlist: {
      eyebrow: 'DANH SÁCH DỰ BỊ',
      title: 'ĐĂNG KÝ DỰ BỊ',
      description: 'Kèo hiện đã đầy. Bạn có thể đăng ký dự bị để được ưu tiên nếu có thành viên rời kèo.',
      submit: 'Đăng ký dự bị',
    },
    skill_warning: {
      title: 'CHÊNH LỆCH TRÌNH ĐỘ',
      description: 'Trình độ của bạn thấp hơn yêu cầu của kèo này. Host có quyền từ chối nếu muốn đảm bảo chất lượng trận đấu.',
    },
    intro: {
      title: 'LỜI CHÀO (TÙY CHỌN)',
      description: 'Hãy giới thiệu ngắn gọn về bản thân để host tin tưởng hơn nhé.',
      placeholder_request: 'Chào host, mình muốn tham gia kèo này...',
      placeholder_waitlist: 'Mình muốn đăng ký dự bị, nếu có slot báo mình nhé!',
    },
    privacy: {
      title: 'QUYỀN RIÊNG TƯ',
      description: 'Thông tin liên hệ (số điện thoại) của bạn sẽ chỉ hiển thị với thành viên trong kèo sau khi bạn được chấp nhận.',
    },
  },
  date: {
    today: 'Hôm nay',
    tomorrow: 'Ngày mai',
    weekdays: {
      0: 'Chủ nhật',
      1: 'Thứ 2',
      2: 'Thứ 3',
      3: 'Thứ 4',
      4: 'Thứ 5',
      5: 'Thứ 6',
      6: 'Thứ 7',
    },
    month: 'Tháng',
    unknown: 'Chưa rõ thời gian',
    finished: 'Trận đấu đã kết thúc',
    ended: 'Kết thúc',
    until: 'đến',
    day_label: 'ngày',
  },
  court: {
    title: 'CHI TIẾT SÂN',
    not_found: 'Không tìm thấy sân.',
    photos: 'ẢNH',
    hours: 'Giờ mở cửa: ',
    status_open: 'ĐANG MỞ',
    status_closed: 'ĐÃ ĐÓNG',
    actions: {
      call: 'Gọi điện',
      directions: 'Chỉ đường',
      explore_sessions: 'Trạng thái sân',
      create_session: 'Tạo kèo tại sân này',
      view_all: 'Tất cả',
      see_more: 'Xem thêm',
    },
    sessions: {
      waiting: '{count} KÈO ĐANG CHỜ',
      empty: 'CHƯA CÓ KÈO MỚI',
      view: 'XEM',
    },
    reviews: {
      title: 'Đánh giá từ người chơi',
      all_reviews: 'Tất cả đánh giá ({count})',
      just_now: 'Vừa xong',
      default_review: 'Sân chơi tuyệt vời, dịch vụ rất tốt.',
    },
  },
  notifications: {
    title: 'THÔNG BÁO',
    new_tag: 'MỚI',
    empty: 'Chưa có thông báo nào',
    empty_description: 'Khi có yêu cầu tham gia, thay đổi kèo hoặc phản hồi mới, bạn sẽ thấy chúng ở đây.',
    categories: {
      all: 'Tất cả',
      my_sessions: 'Kèo của tôi',
      achievements: 'Danh hiệu',
    },
    actions: {
      accept: 'CHẤP NHẬN',
      reject: 'TỪ CHỐI',
    },
  },
  pvna_quiz: {
    title: 'PVNA ASSESSMENT',
    subtitle: 'Đánh giá trình độ chuẩn Quốc gia',
    step_label: 'CÂU HỎI',
    gender_title: 'CHỌN GIỚI TÍNH',
    gender_subtitle: 'PVNA tính điểm khác nhau cho Nam và Nữ để đảm bảo công bằng.',
    gender_nam: 'NAM',
    gender_nu: 'NỮ',
    result_title: 'KẾT QUẢ PVNA',
    confirm_level: 'XÁC NHẬN TRÌNH ĐỘ',
    redo_quiz: 'LÀM LẠI BÀI TEST',
    view_result: 'XEM KẾT QUẢ',
    calculating: 'Đang tính toán kết quả...',
    initial_pvna: 'ĐIỂM PVNA KHỞI ĐIỂM',
    placement_note: 'Đây là điểm số dự phỏng dựa trên kỹ năng của bạn. Điểm số sẽ chính xác hơn sau 5 trận đấu chính thức.',
    level_names: {
      'Beginner': 'Mới chơi',
      'Novice I': 'Tập sự I',
      'Novice II': 'Tập sự II',
      'Novice III': 'Tập sự III',
      'Intermediate I': 'Trung cấp I',
      'Intermediate II': 'Trung cấp II',
      'Intermediate III': 'Trung cấp III',
      'Intermediate+': 'Trung cấp+',
      'Advanced I': 'Khá/Nâng cao I',
      'Advanced II': 'Khá/Nâng cao II',
      'Advanced+': 'Khá/Nâng cao+',
      'Expert I': 'Chuyên gia I',
      'Expert II': 'Chuyên gia II',
      'Expert+': 'Chuyên gia+',
      'Elite I': 'Tinh anh I',
      'Elite II': 'Tinh anh II',
      'Pro I': 'Chuyên nghiệp I',
    },
  },
  register: {
    title: 'ĐĂNG KÝ VÀO KÈO',
    success_title: 'ĐĂNG KÝ THÀNH CÔNG',
    player_info: 'THÔNG TIN NGƯỜI CHƠI',
    name_label: 'Họ và tên',
    name_hint: 'Dùng đúng họ tên để chủ sân dễ xác nhận.',
    phone_label: 'Số điện thoại',
    phone_hint: 'Nhập 10 số bắt đầu bằng 0 hoặc 84xxxxxxxx.',
    gender_label: 'Giới tính',
    partner_pref: 'Bạn đồng hành (Partner)',
    opponent_pref: 'Đối thủ (Opponent)',
    skill_level_label: 'Điểm trình PVNA',
    skill_helper_newbie: '* Bạn đã chọn chế độ Người mới chơi.',
    skill_helper_slider: 'Kéo thanh trượt để chọn mức phù hợp. Nếu mới chơi, chọn thấp trong khoảng.',
    skill_assessment_prompt: 'Bạn không biết điểm trình của mình? ',
    skill_assessment_link: 'Làm ngay bài đánh giá của PVNA để biết trình độ',
    ended_warning: '⚠️ Kèo đấu này đã kết thúc hoặc không còn nhận đăng ký.',
    submitting: 'ĐANG XỬ LÝ...',
    confirm_btn: 'Xác nhận tham gia',
    db_connecting: 'Đang kết nối Database (vui lòng đợi)...',
    db_timeout: 'KẾT NỐI QUÁ HẠN: Server không phản hồi sau 15 giây.',
    loading_data: 'Đang chuẩn bị dữ liệu...',
    saving_info: 'Đang lưu thông tin cá nhân...',
    success: 'Thành công!',
  },
  session_card: {
    status_full: 'ĐÃ ĐẦY',
    status_need_players: 'CẦN THÊM NGƯỜI',
    status_open: 'ĐANG MỞ',
    status_playing: 'ĐANG THI ĐẤU',
    status_playing_match: 'THI ĐẤU',
    status_cancelled: 'ĐÃ HỦY',
    status_done: 'KẾT THÚC',
    status_upcoming: 'SẮP ĐÁNH',
    status_history: 'LỊCH SỬ',
    status_win: 'THẮNG',
    status_loss: 'THUA',
    status_pending: 'CHỜ DUYỆT',
    host_role: 'CHỦ KÈO',
    format_social: 'GIAO LƯU SOCIAL',
    default_court_name: 'SÂN PICKLEBALL',
    default_court_title: 'KÈO PICKLEBALL',
    no_address: 'Chưa cập nhật địa chỉ',
    today: 'Hôm nay',
    tomorrow: 'Ngày mai',
    days: ['Chủ nhật', 'Thứ 2', 'Thứ 3', 'Thứ 4', 'Thứ 5', 'Thứ 6', 'Thứ 7'],
    time_label: 'THỜI GIAN',
    cost_label: 'CHI PHÍ',
    free: 'Miễn phí',
    per_person: '/ người',
    time_to: 'đến {time}',
    details_btn: 'CHI TIẾT',
    court_number: 'SÂN {number}',
  },
  session_empty: {
    upcoming: {
      eyebrow: 'SẴN SÀNG RA SÂN',
      title: 'Bạn chưa có kèo sắp tới',
      description: 'Tạo kèo mới hoặc tham gia một trận phù hợp để lịch chơi của bạn bắt đầu đầy lên.',
    },
    pending: {
      eyebrow: 'ĐANG CHỜ',
      title: 'Chưa có yêu cầu nào cần duyệt',
      description: 'Những kèo bạn đang chờ chủ kèo phản hồi sẽ xuất hiện tại đây.',
    },
    history: {
      eyebrow: 'LỊCH SỬ THI ĐẤU',
      title: 'Bạn chưa có lịch sử trận đấu',
      description: 'Sau khi hoàn thành các trận đã chơi, phần lịch sử sẽ hiển thị tại đây.',
    },
  },
  session_arrangement: {
    invalid_teams: {
      title: 'Đội hình không hợp lệ',
      message: 'Mỗi đội chỉ được phép có tối đa {count} người cho kèo {type}.',
      type_double: 'đánh đôi',
      type_single: 'đánh đơn',
      understand: 'Đã hiểu',
    },
    save_failed: {
      title: 'Không lưu được đội',
      understand: 'Đã hiểu',
    },
    save_success: {
      title: 'Đã lưu thay đổi',
      message: 'Đội hình đã được cập nhật.',
      understand: 'Đã hiểu',
    },
  },
  find_session: {
    dialogs: {
      network_error: {
        title: 'Lỗi kết nối',
        message: 'Không thể cập nhật danh sách kèo lúc này. Vui lòng thử lại.',
        understand: 'Đã hiểu',
      },
      permission_location: {
        title: 'Quyền truy cập',
        message: 'Vui lòng cho phép ứng dụng truy cập vị trí để tìm các kèo gần bạn.',
        understand: 'Đã hiểu',
      },
      location_error: {
        title: 'Lỗi',
        message: 'Không thể xác định vị trí của bạn lúc này.',
        understand: 'Đã hiểu',
      },
      complete_profile: {
        title: 'Cần hoàn thiện hồ sơ',
        message: 'Gợi ý hợp gu cần thành phố và mức trình gần đúng để ưu tiên kèo phù hợp hơn.',
        cancel: 'Để sau',
        confirm: 'Chỉnh hồ sơ',
      },
    },
  },
  auth_gate: {
    no_connection: 'KHÔNG CÓ KẾT NỐI',
    reconnecting: 'ĐANG KẾT NỐI LẠI...',
    offline_message: 'Vui lòng kiểm tra kết nối mạng của bạn để tiếp tục.',
    unstable_message: 'Kết nối mạng của bạn có vẻ không ổn định. Đang thử lại...',
    retry_now: 'Thử lại ngay',
    reload_page: 'Thử tải lại trang',
    authenticating: 'ĐANG XÁC THỰC...',
    redirecting: 'ĐANG CHUYỂN HƯỚNG...',
    persistence_warning: 'Trình duyệt đang chặn lưu trữ (chế độ ẩn danh). Bạn sẽ bị đăng xuất khi đóng tab này.',
  },
  my_sessions: {
    loading: 'Đang tải kèo của bạn...',
    refreshing: 'Cập nhật lịch thi đấu...',
    sections: {
      today: 'Hôm nay',
      tomorrow: 'Ngày mai',
      later: 'Sắp tới',
      next_session: 'Kèo tiếp theo',
      matches_count: '{count} TRẬN',
    },
    share: {
      body: 'Cùng xem kèo pickleball này nhé:',
      default_message: 'Lịch chơi PickleMatch của tôi đang được cập nhật.',
    },
  },
  host_flow: {
    login_link: 'Bạn là Host? Đăng nhập tại đây',
    claim_title: 'XÁC THỰC HOST',
    claim_sub: 'Tìm kiếm và xác nhận sân của bạn để bắt đầu quản lý.',
    business_name: 'Tên cơ sở kinh doanh',
    business_name_placeholder: 'Ví dụ: Pickleball Club Da Nang',
    contact_phone: 'SĐT liên hệ kinh doanh',
    register_host: 'Đăng ký thông tin Host',
    search_court: 'Tìm tên sân...',
    no_host: 'Chưa có chủ',
    claimed: 'Đã có chủ',
    claim_action: 'Xác nhận Host',
    config_title: 'CẤU HÌNH SÂN',
    config_sub: 'Thiết lập số lượng sân con để hệ thống sắp xếp trận đấu.',
    sub_court_count: 'Số lượng sân con (Units)',
    sub_court_hint: 'Ví dụ: Sân của bạn có 4 sân lẻ, hãy nhập 4.',
    choose_format: {
      title: 'CHỌN HÌNH THỨC',
      sub: 'Chọn cách thức tổ chức phù hợp',
      social_title: 'Fun Social',
      social_desc: 'Giao lưu vui vẻ, tính phí theo đầu người.',
      rr_title: 'Round Robin',
      rr_desc: 'Thi đấu xoay vòng, tự động tính toán theo số sân.',
    },
    dashboard: {
      title: 'QUẢN LÝ SÂN',
      requests: 'Chờ duyệt',
      participants: 'Tham gia',
      results: 'Kết quả',
      approve: 'Duyệt',
      reject: 'Từ chối',
      check_in: 'Điểm danh',
    },
    team_arrangement: {
      not_enough_players: 'Chưa đủ đội',
      invalid_team_count: 'Mỗi đội cần đúng 2 người. Đội cần chỉnh: {info}',
      waiting_no_partner: 'CÓ {count} NGƯỜI CHƯA CÓ CẶP',
      waiting_no_partner_hint: '{names} sẽ ngồi ngoài lịch cố định cặp. Chuyển sang Xoay vòng nếu muốn tất cả người chơi được xếp trận.',
    },
    check_in: {
      alert_incomplete: 'Chưa hoàn tất',
      alert_confirm_all: 'Vui lòng xác nhận trạng thái cho tất cả người chơi.',
      start: 'BẮT ĐẦU ĐIỂM DANH',
      complete: 'HOÀN TẤT ĐIỂM DANH',
      transition_confirm: 'Sau khi hoàn tất Check-in, bạn sẽ chuyển sang màn Quản lý trận để sắp lịch theo hình thức chơi. Tiếp tục?',
      confirm_message: 'Sau khi hoàn tất Check-in, bạn sẽ không thể chỉnh sửa hoặc hủy kèo này nữa. Tiếp tục?',
      confirm_title: 'Xác nhận hoàn tất',
      error_complete: 'Không thể hoàn tất check-in.',
      no_players: 'Chưa có người chơi nào được xác nhận.',
    },
    suggester: {
      insufficient_players: 'Chỉ đủ người cho một phần số sân',
      sync_list: 'ĐỒNG BỘ DANH SÁCH (SYNC)',
      sync_required_hint: 'Chưa có danh sách người chơi. Bấm ĐỒNG BỘ (SYNC) để bắt đầu.',
      repeat_warning: 'Setup này có thể tạo trùng lặp. Host có thể giảm sân, giảm vòng, hoặc giữ nguyên nếu ưu tiên chơi nhiều.',
      undo_reason: 'Đã đổi lựa chọn vòng: {reason}',
      warning_not_enough_present: 'Không đủ 4 người đang có mặt',
      warning_over_capacity: 'Nhiều người cần vào sân hơn số slot',
      warning_no_valid_match: 'Chưa có cặp đấu cân PVNA hợp lệ',
      warning_partial_courts: 'Chỉ đủ người cho một phần số sân',
      warning_manual_swap: 'Đã chỉnh tay',
      no_group: 'Chưa có group',
    },
  },
} as const
