import fs from 'fs'

import type { SimulationResult } from '../runner'
import { STYLES, SCRIPTS } from './styles'
import {
  escapeText,
  renderAdjustmentTimeline,
  renderBreakdown,
  renderEvolution,
  renderHeader,
  renderPairHistoryHeatmaps,
  renderPerPlayer,
  renderPerformance,
  renderRounds,
  renderSummaryCards,
  renderWarnings,
} from './templates'

export type ReportOptions = {
  output_path: string
  include_round_details: boolean
  include_per_player: boolean
  include_evolution_chart: boolean
  include_adjustments: boolean
  theme: 'light' | 'dark'
}

const DEFAULT_OPTIONS: ReportOptions = {
  output_path: 'simulation-report.html',
  include_round_details: true,
  include_per_player: true,
  include_evolution_chart: true,
  include_adjustments: true,
  theme: 'light',
}

export function generateHTMLReport(
  result: SimulationResult,
  options: Partial<ReportOptions> = {},
): string {
  const opts = { ...DEFAULT_OPTIONS, ...options }
  const sections = [
    renderHeader(result),
    renderSummaryCards(result),
    renderBreakdown(result),
    opts.include_evolution_chart ? renderEvolution(result) : '',
    opts.include_per_player ? renderPerPlayer(result) : '',
    opts.include_per_player ? renderPairHistoryHeatmaps(result) : '',
    opts.include_round_details ? renderRounds(result) : '',
    opts.include_adjustments ? renderWarnings(result) : '',
    opts.include_adjustments ? renderAdjustmentTimeline(result) : '',
    renderPerformance(result),
  ].join('')

  return wrapDocument(sections, result.config.scenario_name ?? 'Simulation Report', opts.theme)
}

export function saveHTMLReport(
  result: SimulationResult,
  path: string,
  options: Partial<ReportOptions> = {},
): void {
  fs.writeFileSync(path, generateHTMLReport(result, { ...options, output_path: path }), 'utf8')
}

export function generateComparisonReport(
  results: SimulationResult[],
  labels: string[],
  options: Partial<ReportOptions> = {},
): string {
  const cards = results
    .map((result, index) => {
      const label = labels[index] ?? `Result ${index + 1}`
      return `<section><h2>${escapeText(label)}</h2>${renderSummaryCards(result)}${renderBreakdown(result)}${renderPerformance(result)}</section>`
    })
    .join('')

  return wrapDocument(`<header><div><h1>Simulation Comparison</h1><p class="muted">${results.length} runs</p></div></header><div class="grid2">${cards}</div>`, 'Simulation Comparison', options.theme ?? 'light')
}

function wrapDocument(body: string, title: string, theme: ReportOptions['theme']): string {
  return `<!doctype html><html lang="en" data-theme="${theme}"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>${escapeText(title)}</title><style>${STYLES}</style></head><body><main>${body}<div class="footer">Generated by PickleMatch simulation reporter. Standalone offline HTML.</div></main><script>${SCRIPTS}</script></body></html>`
}
